### ISSUE TITLE
Underscores do not work with translation.

### ISSUE THREAD

**Issue by spikehidden** [Lorenzo0111/MultiLang#88]
When using underscores (`_`) in the identifier "`<lang>quest_newbie_hungry_07</lang>`" won't be replaced with the actual string. It will show `<lang>quest_newbie_hungry_07</lang>`.
#### Example:
```yml
  7687:
    identifier: "quest_newbie_hungry_07"
    default: "See you later"
    locales:
      english: "See you later"
      deutsch: "Bis später"
      deutsch_be: "Bis später"
```
But if I change the config to
```yml
  7687:
    identifier: "questnewbiehungry07"
    default: "See you later"
    locales:
      english: "See you later"
      deutsch: "Bis später"
      deutsch_be: "Bis später"
```
it will show `See you later` or `Bis später`.
![image](https://user-images.githubusercontent.com/31257733/179374378-c402567c-16de-4cd8-aa2a-2dca65533bb9.png)
